name: Java compile check
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Find .java files and compile
        run: |
          set -e
          echo "Searching for .java files..."
          files=$(find . -name "*.java" -not -path "./.git/*")
          if [ -z "$files" ]; then
            echo "No Java files found."
            exit 0
          fi
          echo "Compiling java files..."
          javac $files
          echo "Compilation successful"
